spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/astami
    username: postgres
    password: 1954623790
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
jwt:
  secret-key: '{"kty": "oct", "k": "kL9yZ1mB5aV4bU9qH4mO0wN5hT3cL6gP2xV1cU5wA7oH9xV7qW8oA6hG5bU4l"}'
  access-token-expiration: '30d'
  refresh-token-expiration: '30d'
logging:
  level:
    org.springframework.security: TRACE

